language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower web-component-tester
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - CXX=g++-4.8
  - secure: A/43hbztiyJtHzoL9TgClf/940bkiOZTnrGNp/m6q+ZIAi5KigVQfSvfiu4ickXCUuXzjwjpvcK7/sQsaynpJIGQbFnmNbobQrIh6NUqd0Ons6N0uddwqMKYdxx9VAy+H5rK0pWT7IOSoWohDQCxNXM9pdbJTn2dxRklOH/AuPTt7Ary4L4ikAfekSYuauL1YFodsfd+qxzymEcbw7ungAX/bRE9qyXzb1bHlL90EypVV2mrmr0YI63uRCuI1MSokRRnH7LZBOjBhYrKqbZrXIabf6jvtqrRian78P5q6+RwW0j/EPEB6GoiZbrKH5gWAp8+1Qcj4X1AnmUl0DPA/IjtGHbvG+v3CnUsdF9sqfsdeyb4ltasqGHpJA8nE1nhSWqQd8ncFpOJHC+DKroAxWqemUfL6rOD+L1d41c3hr+UZcpJmRhWW8lVfb9VVTzfH2FRYiXKhIQpXTSSbUjz+MkC73CXEYm4zhOxpRpNg+5DSUgt2NSks/s8UOEzZMUDj4FoY6BRd2QzFa6XWVKtsB8sC8XOhOyIZHfRnhAxPYbe1Mxhd1OEot8x6OcmVkEFm+ZP/3Yexl8+1E0zq0ur8WqAYkPHmhfG+0msIBygBthTyhPAWIx36ZxopBHaDpRoIhQ/jFgeRUuYgAQm23PwX4fvN+09FpOEg20yHjZb8lQ=
  - secure: Lg9QNjkL7N0Xd3wCao03LKhHeDdznSx0tWXrRWEWHKmdob9x2ZcztZNbX6dbDhR0iU2Wv/hP3xQn8W6AxYWS3cG3Gq2mqV31EIG1cXMGSK8HlMtNpKSCGW0yXR1BwXrqoEf8tPt5ZMWa0ocr6in0SKsLVvTOLoKkP6xYsJd4pzcgX20SR4OpDWsGRfSibRYovishQIvCKjT3L7KLf54B/DOWh+y/g/F2sUJMEEEE0FGd7lDw7nQQPzOOqI0tqdiVum4zqUAm9vGsVNoIUcH+bQiISCQcH54xKJCeAo3NZOGqAPINsyQE4o4+zd0kyG7ovm4VeqwIIRdhHFxriEvb69HW2X0uzeXEjdmzmevUmjuC/EEUPdgedkf8EKx7mYAD3PZzpct0rMxVnWUD2utmgeXR++D9T7GfgptUv6NO75/9ikyIHSRkXzLhbmFnsv7Sq1CLTUrF8ghIzTZh+JLJVnobqtzGpBWjjzhG+2m/7RnsuZwsHLHkoWuaGBrzUwatu8XGS7JdoOlWxduJx5V/XnrIwjLNnjIwRkWOBrb6s1p99qF+4qRrLTxU2S5SVOZrFkkC4NMY0FFuxH5OesciFadjRRSnMh26VBKaWS/zrQSrIoPUrTOL22PjaXpQpt8nD4xbRT+ecIKw+To2kfFp+7tAbo2hn8mxHeI24CNUzWg=
